#!/usr/bin/python
# swift-dul-daemon - Simple git-daemon-like server
# Copyright (C) 2013 eNovance SAS <licensing@enovance.com>
#
# Author: Fabien Boucher <fabien.boucher@enovance.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; version 2
# or (at your option) a later version of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.

import logging
import eventlet

from dulwich import log_utils
from dulwich.server import (
        TCPGitServer,
        Backend,
        )

from dulwich.swift import (
        SwiftConnector,
        SwiftRepo,
        load_conf,
        )

eventlet.monkey_patch(all=False, socket=True)
conf = load_conf()

class SwiftSystemBackend(Backend):
    """Simple backend that looks up Git repositories in the local file system."""

    def open_repository(self, path):
        #logger.debug('opening repository at %s', path)
        return SwiftRepo(path, conf)

if __name__ == '__main__':
    log_utils.default_logging_config()
    log_utils.getLogger().setLevel(logging.INFO)
    backend = SwiftSystemBackend()
    server = TCPGitServer(backend, '0.0.0.0')
    server.serve_forever()
